[versions]
kotlin = "2.3.20-Beta2"
ktor = "3.4.0"
kotlinx-serialization = "1.10.0"
apollo = "5.0.0-alpha.4"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dockerJavaApplication = { id = "com.bmuschko.docker-java-application", version = "9.4.0" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }

[libraries]
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-defaultHeaders = { group = "io.ktor", name = "ktor-server-default-headers", version.ref = "ktor" }
ktor-server-statusPages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-server-contentNegotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-websockets = { group = "io.ktor", name = "ktor-server-websockets", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
klibminitel = "org.jraf.klibminitel:klibminitel:1.4.1-SNAPSHOT"
apollo-runtime = { group = "com.apollographql.apollo", name = "apollo-runtime", version.ref = "apollo" }
apollo-adapters-core = "com.apollographql.adapters:apollo-adapters-core:0.7.0"
slf4j-simple = "org.slf4j:slf4j-simple:2.0.17"
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
markdown = "org.jetbrains:markdown:0.7.3"
klibslack = "org.jraf.klibslack:klibslack:1.0.2"
jsoup = "org.jsoup:jsoup:1.22.1"
